#요따 해야되네

name: 'CI'

on:
  push:
    branches: ['main', 'mytest']
  pull_request:
    branches: ['main']
  issue_comment:
    types: [created]

jobs:
  tests:
    if: contains(github.event.comment.body, '테스트 실패')
    runs-on: ubuntu-latest
    steps:
      # Repository로부터 CI 수행 서버로 코드를 내려받는 Action
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        # jdk를 다운 받고 캐싱해주는 Action
        uses: actions/setup-java@v3
        # Action에 전달하는 input을 정의하는 곳
        with:
          java-version: 17
          distribution: 'temurin'
          
      - name: 테스트 실패 시, 실패한 코드 라인에 Check 코멘트를 등록합니다
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: '**/build/classes/java/test/org/example/MemberTest.class'


  ci:
    runs-on: ubuntu-latest
    steps:
      # Repository로부터 CI 수행 서버로 코드를 내려받는 Action
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        # jdk를 다운 받고 캐싱해주는 Action
        uses: actions/setup-java@v3
        # Action에 전달하는 input을 정의하는 곳
        with:
          java-version: 17
          distribution: 'temurin'


     # Gradle을 이용해 빌드하고 CI 속도를 높히기 위하여 의존하는 라이브러리들을 캐싱
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
